env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  no-console: 0
  no-await-in-loop: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
